import path from 'node:path';
import { BaseGenerator } from './base.generator.js';
import { type CliOptions, type FileDefinition, type GeneratorResult } from '../types.js';
import { logger } from '../utils/logger.js';
import { mergeDeps, applyExtras } from '../shared/packages.js';

function getNextjsPackageJson(options: CliOptions): Record<string, unknown> {
  const base = {
    name: 'frontend',
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint',
    },
    dependencies: {
      next: '^16.2.9',
      react: '^19.2.7',
      'react-dom': '^19.2.7',
    },
    devDependencies: {
      '@types/node': '^24.13.2',
      '@types/react': '^19.2.17',
      '@types/react-dom': '^19.2.3',
      typescript: '~6.0.2',
      'eslint-config-next': '^16.0.0',
    },
  };
  return mergeDeps(base, options, false) as Record<string, unknown>;
}

const NEXTJS_TS_CONFIG = {
  compilerOptions: {
    target: 'ES2017',
    lib: ['dom', 'dom.iterable', 'esnext'],
    allowJs: true,
    skipLibCheck: true,
    strict: true,
    noEmit: true,
    esModuleInterop: true,
    module: 'esnext',
    moduleResolution: 'bundler',
    resolveJsonModule: true,
    isolatedModules: true,
    jsx: 'preserve',
    incremental: true,
    plugins: [{ name: 'next' }],
    paths: {
      '@/*': ['./src/*'],
    },
  },
  include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
  exclude: ['node_modules'],
};

export class NextjsGenerator extends BaseGenerator {
  async generate(): Promise<GeneratorResult> {
    logger.step('Generating Next.js + TypeScript project...');

    const dir = this.resolvePath(this.options.frontendDirName);
    const files: FileDefinition[] = this.getFiles(dir);

    await this.writeFiles(files);

    logger.success(`Next.js project created in ${dir}`);
    return { filesCreated: files.length, dir };
  }

  private getFiles(dir: string): FileDefinition[] {
    const files: FileDefinition[] = [
      {
        path: path.join(dir, 'package.json'),
        content: this.formatJson(getNextjsPackageJson(this.options)),
      },
      {
        path: path.join(dir, 'tsconfig.json'),
        content: this.formatJson(NEXTJS_TS_CONFIG),
      },
      {
        path: path.join(dir, 'next.config.ts'),
        content: `import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  /* config options here */
};

export default nextConfig;
`,
      },
      {
        path: path.join(dir, 'app', 'layout.tsx'),
        content: `import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next.js App',
  description: 'Generated by create-scaffold',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
`,
      },
      {
        path: path.join(dir, 'app', 'page.tsx'),
        content: `import Link from 'next/link';

export default function Home() {
  return (
    <div className="container">
      <header className="hero">
        <h1 className="hero-title">Next.js + TypeScript</h1>
        <p className="hero-subtitle">
          Scaffolded with create-scaffold. Start building your app!
        </p>
        <div className="hero-actions">
          <Link href="/docs" className="btn btn-primary">
            Get Started
          </Link>
          <a
            href="https://nextjs.org/docs"
            target="_blank"
            rel="noopener noreferrer"
            className="btn btn-secondary"
          >
            Next.js Docs
          </a>
        </div>
      </header>

      <main className="features">
        <div className="feature-card">
          <h2>App Router</h2>
          <p>Built on the modern App Router pattern with server components.</p>
        </div>
        <div className="feature-card">
          <h2>TypeScript</h2>
          <p>Full type safety with strict TypeScript configuration.</p>
        </div>
        <div className="feature-card">
          <h2>Responsive</h2>
          <p>Mobile-first responsive design with CSS Grid and Flexbox.</p>
        </div>
      </main>

      <footer className="footer">
        <p>Powered by Next.js</p>
      </footer>
    </div>
  );
}
`,
      },
      {
        path: path.join(dir, 'app', 'globals.css'),
        content: `:root {
  --color-primary: #0070f3;
  --color-primary-dark: #0051b3;
  --color-bg: #ffffff;
  --color-bg-secondary: #f5f5f5;
  --color-text: #1a1a1a;
  --color-text-secondary: #666666;
  --color-border: #e0e0e0;
  --max-width: 1100px;
  --border-radius: 8px;
}

@media (prefers-color-scheme: dark) {
  :root {
    --color-primary: #3291ff;
    --color-primary-dark: #0070f3;
    --color-bg: #0a0a0a;
    --color-bg-secondary: #1a1a1a;
    --color-text: #e0e0e0;
    --color-text-secondary: #999999;
    --color-border: #333333;
  }
}

* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

html {
  scroll-behavior: smooth;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen,
    Ubuntu, Cantarell, sans-serif;
  background: var(--color-bg);
  color: var(--color-text);
  line-height: 1.6;
}

.container {
  max-width: var(--max-width);
  margin: 0 auto;
  padding: 0 1rem;
}

.hero {
  text-align: center;
  padding: 4rem 0;
}

.hero-title {
  font-size: 3rem;
  font-weight: 700;
  margin-bottom: 1rem;
  background: linear-gradient(135deg, var(--color-primary), #7928ca);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.hero-subtitle {
  font-size: 1.2rem;
  color: var(--color-text-secondary);
  margin-bottom: 2rem;
}

.hero-actions {
  display: flex;
  gap: 1rem;
  justify-content: center;
}

.btn {
  padding: 0.75rem 1.5rem;
  border-radius: var(--border-radius);
  text-decoration: none;
  font-weight: 500;
  transition: all 0.2s;
}

.btn-primary {
  background: var(--color-primary);
  color: white;
}

.btn-primary:hover {
  background: var(--color-primary-dark);
}

.btn-secondary {
  background: var(--color-bg-secondary);
  color: var(--color-text);
  border: 1px solid var(--color-border);
}

.btn-secondary:hover {
  border-color: var(--color-text);
}

.features {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 1.5rem;
  padding: 2rem 0;
}

.feature-card {
  padding: 2rem;
  background: var(--color-bg-secondary);
  border-radius: var(--border-radius);
  border: 1px solid var(--color-border);
}

.feature-card h2 {
  margin-bottom: 0.75rem;
  font-size: 1.25rem;
}

.feature-card p {
  color: var(--color-text-secondary);
}

.footer {
  text-align: center;
  padding: 2rem 0;
  color: var(--color-text-secondary);
  border-top: 1px solid var(--color-border);
  margin-top: 2rem;
}

@media (max-width: 768px) {
  .hero-title {
    font-size: 2rem;
  }

  .hero-actions {
    flex-direction: column;
    align-items: center;
  }
}
`,
      },
      {
        path: path.join(dir, '.gitignore'),
        content: `# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts
`,
      },
      {
        path: path.join(dir, 'README.md'),
        content: `# Next.js + TypeScript

This project was scaffolded with \`create-scaffold\`.

## Getting Started

\`\`\`bash
pnpm install
pnpm dev
\`\`\`

## Scripts

| Command | Description |
|---------|-------------|
| \`pnpm dev\` | Start development server |
| \`pnpm build\` | Build for production |
| \`pnpm start\` | Start production server |
| \`pnpm lint\` | Lint source files |
`,
      },
      {
        path: path.join(dir, 'next-env.d.ts'),
        content: `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// see https://nextjs.org/docs/app/api-reference/config/typescript for more information.
`,
      },
      {
        path: path.join(dir, 'public', '.gitkeep'),
        content: '',
      },
    ];

    // Add extra files from selected packages
    const { files: extraFiles } = applyExtras(this.options, dir);
    files.push(...extraFiles);

    return files;
  }
}
