import path from 'node:path';

import {
  envNextjsMongo,
  envNextjsPostgres,
  GITIGNORE_NEXTJS,
  TSCONFIG_NEXTJS,
} from '../shared/configs.js';
import {
  nextEnvDTsFile,
  pinoLoggerFile,
  prismaClientFile,
  prismaSchemaFile,
} from '../shared/file-snippets.js';
import { addDatabaseDeps, mergeDeps } from '../shared/packages.js';
import { type CliOptions, type FileDefinition } from '../types.js';
import { BaseGenerator } from './base.generator.js';

function getNextjsPackageJson(options: CliOptions): Record<string, unknown> {
  const isFullstack = options.projectType === 'fullstack-nextjs';
  const base: Record<string, unknown> = {
    name: isFullstack ? options.projectName : 'frontend',
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint',
    },
    dependencies: {
      next: '^16.2.9',
      react: '^19.2.7',
      'react-dom': '^19.2.7',
    },
    devDependencies: {
      '@types/node': '^24.13.2',
      '@types/react': '^19.2.17',
      '@types/react-dom': '^19.2.3',
      typescript: '~6.0.2',
      'eslint-config-next': '^16.0.0',
    },
  };

  if (isFullstack) {
    addDatabaseDeps(
      base as unknown as {
        dependencies: Record<string, string>;
        devDependencies: Record<string, string>;
        scripts: Record<string, string>;
      },
      options.database
    );
  }

  return mergeDeps(base, options, isFullstack) as Record<string, unknown>;
}

export class NextjsGenerator extends BaseGenerator {
  private get isFullstack(): boolean {
    return this.options.projectType === 'fullstack-nextjs';
  }

  protected getStepLabel(): string {
    const dbLabel = this.options.database === 'postgresql' ? 'PostgreSQL' : 'MongoDB';
    return this.isFullstack
      ? `Next.js full-stack (API routes + ${dbLabel})`
      : 'Next.js + TypeScript';
  }

  protected getTargetDir(): string {
    return this.isFullstack
      ? this.options.projectDir
      : this.resolvePath(this.options.frontendDirName);
  }

  protected getSuccessMessage(dir: string): string {
    return `Next.js project created in ${dir}`;
  }

  private ifFullstack<T>(items: T[]): T[] {
    return this.isFullstack ? items : [];
  }

  protected buildFiles(dir: string): FileDefinition[] {
    const isPostgres = this.options.database === 'postgresql';
    const files: FileDefinition[] = [
      {
        path: path.join(dir, 'package.json'),
        content: this.formatJson(getNextjsPackageJson(this.options)),
      },
      {
        path: path.join(dir, 'tsconfig.json'),
        content: this.formatJson(TSCONFIG_NEXTJS),
      },
      {
        path: path.join(dir, 'next.config.ts'),
        content: `import type { NextConfig } from 'next';\n\nconst nextConfig: NextConfig = {};\n\nexport default nextConfig;\n`,
      },
      {
        ...nextEnvDTsFile(),
        path: path.join(dir, nextEnvDTsFile().path),
      },
      {
        path: path.join(dir, '.gitignore'),
        content: GITIGNORE_NEXTJS,
      },
      {
        path: path.join(dir, 'README.md'),
        content: this.isFullstack
          ? `# ${this.options.projectName}\n\nA full-stack Next.js application scaffolded with \`create-scaffold\`.\n\n## Getting Started\n\n1. Copy \`.env.example\` to \`.env\` and configure your database connection string.\n2. Install dependencies:\n\n\`\`\`bash\npnpm install\n\`\`\`\n\n3. Start the development server:\n\n\`\`\`bash\npnpm dev\n\`\`\`\n\n## API Endpoints\n\n- \`GET /api/health\` - Health check\n- \`GET /api/users\` - Get all users\n- \`POST /api/users\` - Create a new user\n- \`GET /api/users/[id]\` - Get user by ID\n- \`PUT /api/users/[id]\` - Update a user\n- \`DELETE /api/users/[id]\` - Delete a user\n`
          : `# ${this.options.projectName}\n\nA Next.js project scaffolded with \`create-scaffold\`.\n\n## Getting Started\n\n\`\`\`bash\npnpm install\npnpm dev\n\`\`\`\n`,
      },
      ...this.ifFullstack([
        {
          path: path.join(dir, '.env.example'),
          content: isPostgres ? envNextjsPostgres() : envNextjsMongo(),
        },
      ]),
      ...(this.isFullstack && isPostgres
        ? [
            {
              path: path.join(dir, 'prisma', 'schema.prisma'),
              content: prismaSchemaFile(),
            },
          ]
        : []),
      {
        path: path.join(dir, 'app', 'layout.tsx'),
        content: `import type { Metadata } from 'next';\nimport { Inter } from 'next/font/google';\nimport './globals.css';\n\nconst inter = Inter({ subsets: ['latin'] });\n\nexport const metadata: Metadata = {\n  title: '${this.isFullstack ? 'Next.js Fullstack App' : 'Next.js App'}',\n  description: 'Generated by create-scaffold',\n};\n\nexport default function RootLayout({\n  children,\n}: {\n  children: React.ReactNode;\n}) {\n  return (\n    <html lang="en">\n      <body className={inter.className}>{children}</body>\n    </html>\n  );\n}\n`,
      },
      {
        path: path.join(dir, 'app', 'page.tsx'),
        content: this.isFullstack
          ? `import Link from 'next/link';\n\nexport default function Home() {\n  return (\n    <div className="container">\n      <header className="hero">\n        <h1 className="hero-title">Next.js + ${isPostgres ? 'PostgreSQL' : 'MongoDB'}</h1>\n        <p className="hero-subtitle">Full-stack application scaffolded with create-scaffold.</p>\n        <div className="hero-actions">\n          <Link href="/api/health" className="btn btn-primary">Check API Health</Link>\n          <a href="https://nextjs.org/docs" target="_blank" rel="noopener noreferrer" className="btn btn-secondary">Next.js Docs</a>\n        </div>\n      </header>\n      <main className="features">\n        <div className="feature-card">\n          <h2>App Router</h2>\n          <p>Built on the modern App Router pattern with server components and API routes.</p>\n        </div>\n        <div className="feature-card">\n          <h2>${isPostgres ? 'PostgreSQL + Prisma' : 'MongoDB + Mongoose'}</h2>\n          <p>Integrated ${isPostgres ? 'PostgreSQL connection with Prisma ORM' : 'MongoDB connection with Mongoose models'} and validation.</p>\n        </div>\n        <div className="feature-card">\n          <h2>REST API</h2>\n          <p>Built-in API routes for CRUD operations with proper error handling.</p>\n        </div>\n      </main>\n      <footer className="footer"><p>Powered by Next.js</p></footer>\n    </div>\n  );\n}\n`
          : `import Link from 'next/link';\n\nexport default function Home() {\n  return (\n    <div className="container">\n      <header className="hero">\n        <h1 className="hero-title">Next.js + TypeScript</h1>\n        <p className="hero-subtitle">Scaffolded with create-scaffold. Start building your app!</p>\n        <div className="hero-actions">\n          <Link href="/docs" className="btn btn-primary">Get Started</Link>\n          <a href="https://nextjs.org/docs" target="_blank" rel="noopener noreferrer" className="btn btn-secondary">Next.js Docs</a>\n        </div>\n      </header>\n      <main className="features">\n        <div className="feature-card">\n          <h2>App Router</h2>\n          <p>Built on the modern App Router pattern with server components.</p>\n        </div>\n        <div className="feature-card">\n          <h2>TypeScript</h2>\n          <p>Full type safety with strict TypeScript configuration.</p>\n        </div>\n        <div className="feature-card">\n          <h2>Responsive</h2>\n          <p>Mobile-first responsive design with CSS Grid and Flexbox.</p>\n        </div>\n      </main>\n      <footer className="footer"><p>Powered by Next.js</p></footer>\n    </div>\n  );\n}\n`,
      },
      {
        path: path.join(dir, 'app', 'globals.css'),
        content: `:root {\n  --color-primary: #0070f3;\n  --color-primary-dark: #0051b3;\n  --color-bg: #ffffff;\n  --color-bg-secondary: #f5f5f5;\n  --color-text: #1a1a1a;\n  --color-text-secondary: #666666;\n  --color-border: #e0e0e0;\n  --max-width: 1100px;\n  --border-radius: 8px;\n}\n\n@media (prefers-color-scheme: dark) {\n  :root {\n    --color-primary: #3291ff;\n    --color-primary-dark: #0070f3;\n    --color-bg: #0a0a0a;\n    --color-bg-secondary: #1a1a1a;\n    --color-text: #e0e0e0;\n    --color-text-secondary: #999999;\n    --color-border: #333333;\n  }\n}\n\n* { box-sizing: border-box; margin: 0; padding: 0; }\nhtml { scroll-behavior: smooth; }\nbody { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif; background: var(--color-bg); color: var(--color-text); line-height: 1.6; }\n.container { max-width: var(--max-width); margin: 0 auto; padding: 0 1rem; }\n.hero { text-align: center; padding: 4rem 0; }\n.hero-title { font-size: 3rem; font-weight: 700; margin-bottom: 1rem; background: linear-gradient(135deg, var(--color-primary), #7928ca); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; }\n.hero-subtitle { font-size: 1.2rem; color: var(--color-text-secondary); margin-bottom: 2rem; }\n.hero-actions { display: flex; gap: 1rem; justify-content: center; }\n.btn { padding: 0.75rem 1.5rem; border-radius: var(--border-radius); text-decoration: none; font-weight: 500; transition: all 0.2s; }\n.btn-primary { background: var(--color-primary); color: white; }\n.btn-primary:hover { background: var(--color-primary-dark); }\n.btn-secondary { background: var(--color-bg-secondary); color: var(--color-text); border: 1px solid var(--color-border); }\n.btn-secondary:hover { border-color: var(--color-text); }\n.features { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 1.5rem; padding: 2rem 0; }\n.feature-card { padding: 2rem; background: var(--color-bg-secondary); border-radius: var(--border-radius); border: 1px solid var(--color-border); }\n.feature-card h2 { margin-bottom: 0.75rem; font-size: 1.25rem; }\n.feature-card p { color: var(--color-text-secondary); }\n.footer { text-align: center; padding: 2rem 0; color: var(--color-text-secondary); border-top: 1px solid var(--color-border); margin-top: 2rem; }\n@media (max-width: 768px) { .hero-title { font-size: 2rem; } .hero-actions { flex-direction: column; align-items: center; } }\n`,
      },

      // ── API routes (fullstack only) ──
      ...this.ifFullstack([
        {
          path: path.join(dir, 'app', 'api', 'health', 'route.ts'),
          content: `import { NextResponse } from 'next/server';\nimport { logger } from '@/lib/logger';\n\nexport async function GET() {\n  logger.info('Health check requested');\n  return NextResponse.json({ status: 'ok', timestamp: new Date().toISOString() });\n}\n`,
        },
        {
          path: path.join(dir, 'app', 'api', 'users', 'route.ts'),
          content: isPostgres
            ? `import { NextRequest, NextResponse } from 'next/server';\nimport { connectDatabase } from '@/lib/db';\nimport { prisma } from '@/lib/db';\n\nexport async function GET() {\n  try {\n    await connectDatabase();\n    const users = await prisma.user.findMany({ orderBy: { createdAt: 'desc' } });\n    return NextResponse.json({ success: true, count: users.length, data: users });\n  } catch (error) {\n    return NextResponse.json({ success: false, message: (error as Error).message }, { status: 500 });\n  }\n}\n\nexport async function POST(request: NextRequest) {\n  try {\n    await connectDatabase();\n    const body = await request.json();\n    const user = await prisma.user.create({ data: body });\n    return NextResponse.json({ success: true, data: user }, { status: 201 });\n  } catch (error) {\n    return NextResponse.json({ success: false, message: (error as Error).message }, { status: 400 });\n  }\n}\n`
            : `import { NextRequest, NextResponse } from 'next/server';\nimport { connectDatabase } from '@/lib/db';\nimport { User } from '@/lib/models/User';\n\nexport async function GET() {\n  try {\n    await connectDatabase();\n    const users = await User.find().sort({ createdAt: -1 });\n    return NextResponse.json({ success: true, count: users.length, data: users });\n  } catch (error) {\n    return NextResponse.json({ success: false, message: (error as Error).message }, { status: 500 });\n  }\n}\n\nexport async function POST(request: NextRequest) {\n  try {\n    await connectDatabase();\n    const body = await request.json();\n    const user = await User.create(body);\n    return NextResponse.json({ success: true, data: user }, { status: 201 });\n  } catch (error) {\n    return NextResponse.json({ success: false, message: (error as Error).message }, { status: 400 });\n  }\n}\n`,
        },
        {
          path: path.join(dir, 'app', 'api', 'users', '[id]', 'route.ts'),
          content: isPostgres
            ? `import { NextRequest, NextResponse } from 'next/server';\nimport { connectDatabase } from '@/lib/db';\nimport { prisma } from '@/lib/db';\n\nexport async function GET(_request: NextRequest, { params }: { params: Promise<{ id: string }> }) {\n  try {\n    await connectDatabase();\n    const { id } = await params;\n    const user = await prisma.user.findUnique({ where: { id } });\n    if (!user) return NextResponse.json({ success: false, message: 'User not found' }, { status: 404 });\n    return NextResponse.json({ success: true, data: user });\n  } catch (error) {\n    return NextResponse.json({ success: false, message: (error as Error).message }, { status: 500 });\n  }\n}\n\nexport async function PUT(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {\n  try {\n    await connectDatabase();\n    const { id } = await params;\n    const body = await request.json();\n    const user = await prisma.user.update({ where: { id }, data: body });\n    if (!user) return NextResponse.json({ success: false, message: 'User not found' }, { status: 404 });\n    return NextResponse.json({ success: true, data: user });\n  } catch (error) {\n    return NextResponse.json({ success: false, message: (error as Error).message }, { status: 400 });\n  }\n}\n\nexport async function DELETE(_request: NextRequest, { params }: { params: Promise<{ id: string }> }) {\n  try {\n    await connectDatabase();\n    const { id } = await params;\n    await prisma.user.delete({ where: { id } });\n    return NextResponse.json({ success: true, message: 'User deleted successfully' });\n  } catch (error) {\n    return NextResponse.json({ success: false, message: (error as Error).message }, { status: 500 });\n  }\n}\n`
            : `import { NextRequest, NextResponse } from 'next/server';\nimport { connectDatabase } from '@/lib/db';\nimport { User } from '@/lib/models/User';\n\nexport async function GET(_request: NextRequest, { params }: { params: Promise<{ id: string }> }) {\n  try {\n    await connectDatabase();\n    const { id } = await params;\n    const user = await User.findById(id);\n    if (!user) return NextResponse.json({ success: false, message: 'User not found' }, { status: 404 });\n    return NextResponse.json({ success: true, data: user });\n  } catch (error) {\n    return NextResponse.json({ success: false, message: (error as Error).message }, { status: 500 });\n  }\n}\n\nexport async function PUT(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {\n  try {\n    await connectDatabase();\n    const { id } = await params;\n    const body = await request.json();\n    const user = await User.findByIdAndUpdate(id, body, { new: true, runValidators: true });\n    if (!user) return NextResponse.json({ success: false, message: 'User not found' }, { status: 404 });\n    return NextResponse.json({ success: true, data: user });\n  } catch (error) {\n    return NextResponse.json({ success: false, message: (error as Error).message }, { status: 400 });\n  }\n}\n\nexport async function DELETE(_request: NextRequest, { params }: { params: Promise<{ id: string }> }) {\n  try {\n    await connectDatabase();\n    const { id } = await params;\n    const user = await User.findByIdAndDelete(id);\n    if (!user) return NextResponse.json({ success: false, message: 'User not found' }, { status: 404 });\n    return NextResponse.json({ success: true, message: 'User deleted successfully' });\n  } catch (error) {\n    return NextResponse.json({ success: false, message: (error as Error).message }, { status: 500 });\n  }\n}\n`,
        },
      ]),

      // ── lib/ (fullstack only) ──
      ...this.ifFullstack([
        { path: path.join(dir, 'lib', 'logger.ts'), content: pinoLoggerFile() },
        {
          path: path.join(dir, 'lib', 'db.ts'),
          content: isPostgres
            ? prismaClientFile()
            : `import mongoose from 'mongoose';\n\nconst MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/myapp';\n\ninterface CachedConnection {\n  conn: typeof mongoose | null;\n  promise: Promise<typeof mongoose> | null;\n}\n\ndeclare global { var mongooseCache: CachedConnection | undefined; }\n\nconst cached: CachedConnection = global.mongooseCache || { conn: null, promise: null };\nif (!global.mongooseCache) global.mongooseCache = cached;\n\nexport async function connectDatabase(): Promise<typeof mongoose> {\n  if (cached.conn) return cached.conn;\n  if (!cached.promise) cached.promise = mongoose.connect(MONGODB_URI);\n  try {\n    cached.conn = await cached.promise;\n  } catch (error) {\n    cached.promise = null;\n    throw error;\n  }\n  return cached.conn;\n}\n`,
        },
        ...(isPostgres
          ? []
          : [
              {
                path: path.join(dir, 'lib', 'models', 'User.ts'),
                content: `import mongoose, { Document, Schema } from 'mongoose';\n\nexport interface IUser extends Document {\n  name: string;\n  email: string;\n  createdAt: Date;\n  updatedAt: Date;\n}\n\nconst userSchema = new Schema<IUser>({\n  name: { type: String, required: [true, 'Name is required'], trim: true, minlength: [2, 'Name must be at least 2 characters'], maxlength: [100, 'Name cannot exceed 100 characters'] },\n  email: { type: String, required: [true, 'Email is required'], unique: true, trim: true, lowercase: true, match: [/^\\\\S+@\\\\S+\\\\.\\\\S+$/, 'Please provide a valid email'] },\n}, { timestamps: true });\n\nexport const User = mongoose.model<IUser>('User', userSchema);\n`,
              },
            ]),
        {
          path: path.join(dir, 'lib', 'validators', 'user.ts'),
          content: `export interface ValidationResult { valid: boolean; errors: Record<string, string>; }\n\nexport function validateCreateUser(data: Record<string, unknown>): ValidationResult {\n  const errors: Record<string, string> = {};\n  if (!data.name || typeof data.name !== 'string' || !data.name.trim()) errors.name = 'Name is required';\n  else if (data.name.trim().length < 2) errors.name = 'Name must be at least 2 characters';\n  else if (data.name.trim().length > 100) errors.name = 'Name cannot exceed 100 characters';\n  if (!data.email || typeof data.email !== 'string' || !data.email.trim()) errors.email = 'Email is required';\n  else if (!/^\\\\S+@\\\\S+\\\\.\\\\S+$/.test(data.email as string)) errors.email = 'Please provide a valid email';\n  return { valid: Object.keys(errors).length === 0, errors };\n}\n`,
        },
      ]),

      {
        path: path.join(dir, 'public', '.gitkeep'),
        content: '',
      },
    ];

    return files;
  }
}
